config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  resources :articles
  resources :users
  get 'users/:id/articles' => 'users#articles', :as => :user_articles
  get '/' => 'pages#form1'
  get 'articles/new/:id' => 'articles#new', :as => :new_article_creation


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }, format: { with: /\A[a-zA-Z0-9 ]+\z/ , message: "no special characters, only letters and numbers" }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  #validates_format_of :phone_number, :with =>  /\d[0-9]\)*\z/ , :message => "Only positive number without spaces are allowed"
  validates :phone_number, presence: true, format: { with: /[5-9]{1}\d{9}/, message: "bad format" }, length: { :minimum => 10, :maximum => 10 , message: "bad size"}
  belongs_to :user
  validates :user_id, presence: true, numericality: true


end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  before_save {self.email = email.downcase}
  validates :username, presence: true, length: {minimum: 3, maximum: 20 },
            format: { with: /\A[a-zA-Z0-9]+\z/, message: 'cannot have special characters'  },
            uniqueness: { case_sensitive: false }

  VALID_EMAIL_REGEX = /\A(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,8}\.[a-zA-Z]{2,9})\z/i
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
          class ArticlesController < ApplicationController
            $x = 0
            def show
              @article = Article.find(params[:id])
            end

            def index
              @articles = Article.all
            end

            def new
              @article = Article.new
              $x = params[:id]
            end


              def create
                #render plain: params[:article]
                @article = Article.new(article_params)
                @article.user_id = $x
                #phone_number = @article.phone_number
                # if validates_phone_number(get_digits(phone_number))

                if @article.save!
                    flash[:notice] = "Article was created successfully."
                    redirect_to article_path(@article.id)
                else
                  render 'new'
                end

              end

               def edit
                 @article = Article.find(params[:id])
               end

                def update
                  @article = Article.find(params[:id])
                  phone_number = @article.phone_number
                  current_time = Time.zone.now.to_i
                  created_at = @article.created_at.to_i
                  t1= ((current_time - created_at)/1.hours).round.modulo(24)
                  # t2 = (validates_phone_number(get_digits(phone_number)))
                  if (t1 < 24)
                    if @article.update(article_params)
                      flash[:notice] = "Article was updated successfully."
                      flag = 1
                      redirect_to articles_path
                    else
                      flag = 1
                      render 'edit'
                    end
                  end
                  if flag != 1
                    flash[:alert] = "Sorry you can only update data which created within  24 hrs"
                    render 'edit'
                    end
                end


              def destroy
                @article = Article.find(params[:id])
                if @article.destroy
                  flash[:notice] = "Article was deleted successfully."
                end
                redirect_to articles_path
              end
            private
            def article_params
              params.require(:article).permit(:title, :description, :phone_number, :created_at, :updated_at,:user_id)
            end

              def get_digits(phone)
                digits = Array.new
                while phone!=0
                  r= (phone % 10)
                  digits.push(r)
                  phone = phone/10
                end
                return (digits.reverse)
              end

                  def validates_phone_number(arr)
                    if arr[0] == 0 || arr[0] == 1
                      return false
                    end
                    if arr[1] == 9
                      return false
                    end
                    if (arr[0] + arr[1] == 37) || (arr[0] + arr[1] == 96)
                      return false
                    end
                    if (arr[1] + arr[2] == 11)
                      return false
                    end
                    if (arr[3] == 0) || (arr[3] == 1)
                      return false
                    end

                    return true

                  end
          end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def form1

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end


  def create
    @user = User.new(user_params)
    if @user.save!
      flash[:notice] = "User was created successfully."
      redirect_to user_path(@user.id)
    else
      render 'new'
    end

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
      if @user.update(user_params)
        flash[:notice] = "User was updated successfully."
        redirect_to users_path
      else
        render 'edit'
      end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "User was deleted successfully."
    end
    redirect_to users_path
  end

  def articles
    @user = User.find(params[:id])
    @articles = @user.articles
  end
  private
  def user_params
    params.require(:user).permit(:username, :email,:id)
  end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_inline_form.html.erb
<% if @article.errors.any? %>
  <h2>The following errors prevented the article from being edit</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>


<%= form_with(model: @article, local: true, id: dom_id(@article.id, 'inline_form')) do |f| %>

  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :phone_number %><br/>
    <%= f.number_field :phone_number %>
  </p>

  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<% if @article.errors.any? %>
  <h2>The following errors prevented the article from being edit</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>


<%= form_with(model: @article, local: true) do |f| %>

  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :phone_number %><br/>
    <%= f.number_field :phone_number %>
  </p>

  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>

<!--  <p>-->
<!--    <%#= f.label :user_id %><br/>-->
    <%#= f.number_field :user_id %>
<!--  </p>-->



  <p>
    <%= f.submit %>
  </p>

<% end %>
<br/>
<br/>
<%= link_to 'Cancel and return to articles listing', articles_path %>

app/views/articles/edit.js.erb
document.getElementById('<%= dom_id(@article.id) %>').insertAdjacentHTML('afterend', "<%= j render 'inline_form', article: @article %>")

document.getElementById('<%= dom_id(@article.id) %>').style.display = 'none'

app/views/articles/index.html.erb
<h><strong> Articles Listing Page </strong> </h>
<br/>
<br/>
<%#= link_to '<i class="glyphicon glyphicon-plus"></i> Create New Article'.html_safe, new_article_path, class: 'btn btn-default' %>
<br/>
<br/>
<table>
  <thead>
  <tr>
    <th class="text-center">Title</th>
    <th class="text-center">Description</th>
    <th>Phone_number</th>
    <th>Created_at</th>
    <th>Updated_at</th>
    <th>User_id</th>

    <th colspan="3" class="text-center">Action</th>
  </tr>
  </thead>

  <tbody>
   <% @articles.each do |article| %>
   <tr>
    <td><%= best_in_place article, :title %></td>
    <td><%= best_in_place article, :description %></td>
     <td><%= best_in_place article, :phone_number %></td>
     <td><%= article.created_at.to_date %></td>
     <td><%= article.updated_at.to_date %></td>
     <td><%= article.user_id %></td>
     <td><%= link_to '<i class="glyphicon glyphicon-eye-open"></i>'.html_safe, article_path(article.id), class: 'btn btn-default' %></td>
     <td><%= link_to '<i class="glyphicon glyphicon-pencil"></i>'.html_safe, edit_article_path(article.id), class: 'btn btn-default' %></td>
     <td><%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, article_path(article.id), method: :delete, class: 'btn btn-default',data: {confirm: "Are you sure?"} %></td>
   </tr>
   <% end %>
  </tbody>
</table>

<br/>
<br/>

<%= link_to 'Return to users listing', users_path %> |
<%= link_to 'Return to home page', root_path %>

app/views/articles/new.html.erb
<h><strong>Create a new article</strong></h>
<% if @article.errors.any? %>
  <h2>The following errors prevented the article from being saved</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>


<%= form_with scope: :article, url: articles_path, local: true do |f| %>
  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :phone_number %><br/>
    <%= f.number_field :phone_number %>
  </p>

  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>

<!--  <p>-->
<!--    <%#= f.label :user_id %><br/>-->
    <%#= f.number_field :user_id %>
<!--  </p>-->



  <p>
    <%= f.submit %>
  </p>
<% end %>

<br/>
<%= link_to 'Return to articles listing', articles_path %> |
<%= link_to 'Return to users listing', users_path %>

app/views/articles/show.html.erb
<br/>

<h>Showing specific article</h>

<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>Description: </strong><%= @article.description %></p>
<p><strong>PhoneNumber: </strong><%= @article.phone_number %></p>
<p><strong>Created_at: </strong><%= @article.created_at %></p>
<p><strong>Updated_at: </strong><%= @article.updated_at %></p>
<p><strong>User_id: </strong><%= @article.user_id %></p>

<%= link_to '<i class="glyphicon glyphicon-pencil"></i>'.html_safe, edit_article_path(@article.id), class: 'btn btn-default' %> |
<%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, article_path(@article.id), method: :delete, class: 'btn btn-default',data: {confirm: "Are you sure?"} %> |
<%= link_to 'Return to articles listing', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<style>
    table, th, td {
        border:2px solid black;
    }
    h {
        padding-bottom: 4rem;
        margin-left: 300px;
    }

    h1 {
        padding-top: 1rem;
        margin-left: 300px;
    }
    div {
        color: darkgreen;
    }


</style>


  <head>
    <title>ProjectRb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link href="bootstrap-editable/css/bootstrap-editable.css" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div>
  <% flash.each do |name, msg| %>
    <div1 class="alert alert-success">
    <%= msg %>
    </div1>
    <br/>
    <br/>
  <% end %>
  </div>

  <%= yield %>
  <script src="bootstrap-editable/js/bootstrap-editable.js"></script>
  </body>
</html>

app/views/pages/about.html.erb
<h>Welcome to the About page</h>
<%= link_to 'Articles listing', articles_path %> |
<%= link_to 'Home page', root_path %>

app/views/pages/form1.html.erb
<form class="form-inline">
  <input class="form-control mr-sm-2" type="search" placeholder="Search by name or phone no" aria-label="Search">
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="glyphicon glyphicon-search"></i></button>
</form>

app/views/pages/home.html.erb
<!--<h1>Welcome to the home page</h1>-->
<style>
    nav {
        background-color: red;
        margin-left: -200px;
        margin-right: 0px;
        margin-top: 0px;
    }
    /*span1 {*/
    /*    margin-left: 100px;*/
    /*    margin-top: -30px;*/
    /*    color: #EFEFEF;*/
    /*    text-align: justify-all;*/
    /*    font-size: medium;*/
    /*}*/
    .heading {
        margin-bottom: 100px;
        margin-left: 100px;
        /*margin-top: -10px;*/
        color: #EFEFEF;
        text-align: center;
        font-size: medium;
        content: normal;
    }

    .form-inline {
        margin-top: -32px;
        margin-left: 850px;
        margin-bottom: -30px;
        /*font-size: 2px;*/
    }
    span {
        margin-left: -250px;
        margin-top: 500px;
        margin-bottom: 5px;
        color: #EFEFEF;
    }
    span2 {
        margin-left: 1150px;
        margin-bottom: 100px;
        margin-top: 10px;
        color: #EFEFEF;
        text-align: center;
        font-size: medium;
    }
    .glyphicon.glyphicon-menu-hamburger{
        font-size: large;
        margin-top: 15px;
        margin-bottom: -10px;
        color: #EFEFEF;
    }

    .glyphicon.glyphicon-user{
        font-size: large;
        margin-top: -10px;
        color: #EFEFEF;

    }
</style>
<nav class="navbar navbar-light bg-light">
  <span1 class="heading"> Bharatiya Janta Party</span1>
  <span><%= link_to '<i class="glyphicon glyphicon-menu-hamburger"></i>'.html_safe, articles_path%></span>
  <form class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Search by name or phone no" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="glyphicon glyphicon-search"></i></button>
  </form>
  <span2> vikash kumar <%= link_to '<i class="glyphicon glyphicon-user"></i>'.html_safe, users_path %> </span2>
</nav>
<!--<h1><%#= link_to 'Articles listing', articles_path %></h1>-->

app/views/users/articles.html.erb
<h><strong> Articles Listing Page of specific user</strong> </h>
<br/>
<br/>

<table>
  <thead>
  <tr>
    <th class="text-center">Title</th>
    <th class="text-center">Description</th>
    <th>Phone_number</th>
    <th>Created_at</th>
    <th>Updated_at</th>

    <th colspan="3" class="text-center">Action</th>
  </tr>
  </thead>

  <tbody>
  <% @articles.each do |article| %>
    <tr>
      <td><%= best_in_place article, :title %></td>
      <td><%= best_in_place article, :description %></td>
      <td><%= best_in_place article, :phone_number %></td>
      <td><%= article.created_at.to_date %></td>
      <td><%= article.updated_at.to_date %></td>
      <td><%= link_to '<i class="glyphicon glyphicon-eye-open"></i>'.html_safe, article_path(article.id), class: 'btn btn-default' %></td>
      <td><%= link_to '<i class="glyphicon glyphicon-pencil"></i>'.html_safe, edit_article_path(article.id), class: 'btn btn-default' %></td>
      <td><%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, article_path(article.id), method: :delete, class: 'btn btn-default',data: {confirm: "Are you sure?"} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br/>
<br/>

<%= link_to 'Return to users listing', users_path %>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <h2>The following errors prevented the user from being edit</h2>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>


<%= form_with(model: @user, local: true) do |f| %>

  <p>
    <%= f.label :username %><br/>
    <%= f.text_field :username%>
  </p>

  <p>
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>
<br/>
<br/>
<%= link_to 'Cancel and return to users listing', users_path %>

app/views/users/index.html.erb
<h><strong> Users Listing Page </strong> </h>
<br/>
<br/>
<%= link_to '<i class="glyphicon glyphicon-plus"></i> Create New User'.html_safe, new_user_path, class: 'btn btn-default' %>
<br/>
<br/>
<table>
  <thead>
  <tr>
    <th class="text-center">UserId</th>
    <th class="text-center">Username</th>
    <th class="text-center">Email</th>

    <th colspan="5" class="text-center">Action</th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= best_in_place user, :id %></td>
      <td><%= best_in_place user, :username %></td>
      <td><%= best_in_place user, :email %></td>

      <td><%= link_to '<i class="glyphicon glyphicon-eye-open"></i>'.html_safe, user_path(user.id), method: :get, class: 'btn btn-default' %></td>
      <td><%= link_to '<i class="glyphicon glyphicon-pencil"></i>'.html_safe, edit_user_path(user.id), class: 'btn btn-default' %></td>
      <td><%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, user_path(user.id), method: :delete, class: 'btn btn-default',data: {confirm: "Are you sure?"} %></td>
<!--      <td><%#= link_to '<i class="glyphicon glyphicon-eye-open"></i> articles'.html_safe, user_articles_path(user.id), class: 'btn btn-default' %></td>-->
<!--      <td><%#= link_to '<i class="glyphicon glyphicon-plus"></i> Create New Article'.html_safe, new_article_creation_path(user.id), class: 'btn btn-default' %></td>-->
      <td>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="glyphicon glyphicon-collapse-down"> </i>
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <div><a class="dropdown-item" href="#"> <%= link_to 'Show Articles', user_articles_path(user.id) %></a></div>
            <div><a class="dropdown-item" href="#"> <%= link_to 'Create Article', new_article_creation_path(user.id)%></a></div>
          </div>
        </div>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<br/>
<br/>


<%= link_to 'Return to articles listing', articles_path %> |
<%= link_to 'Return to home page', root_path %>

app/views/users/new.html.erb
<h><strong>Create a new user</strong></h>
<% if @user.errors.any? %>
  <h2>The following errors prevented the user from being saved</h2>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>


<%= form_with scope: :user, url: users_path, local: true do |f| %>
  <p>
    <%= f.label :username %><br/>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<br/>
<%= link_to 'Return to users listing', users_path %>

app/views/users/show.html.erb
<br/>

<h>Showing specific user</h>

<p><strong>Username: </strong><%= @user.username %></p>
<p><strong>Email: </strong><%= @user.email %></p>

<%= link_to '<i class="glyphicon glyphicon-pencil"></i>'.html_safe, user_path(@user.id), class: 'btn btn-default' %> |
<%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, user_path(@user.id), method: :delete, class: 'btn btn-default',data: {confirm: "Are you sure?"} %> |
<%= link_to 'Return to users listing', users_path %>